/**
 * Slack Poster — all outbound Slack messages go through here.
 *
 * Receives the Bolt app instance at init time; never imports server.js.
 */

let _app;

/**
 * Initialise the poster with a configured Slack Bolt App instance.
 * Must be called before any post* functions are used.
 *
 * @param {import('@slack/bolt').App} app
 */
function init(app) {
  _app = app;
}

function requireApp() {
  if (!_app) throw new Error('poster.init(app) must be called before posting messages');
}

/**
 * Post a plain-text message to a channel.
 *
 * @param {string} channelId
 * @param {string} text
 * @returns {Promise<object>} Slack API response
 */
async function postMessage(channelId, text) {
  requireApp();
  return _app.client.chat.postMessage({
    channel: channelId,
    text,
  });
}

/**
 * Post a formatted Block Kit roast message to a channel.
 *
 * @param {string} channelId
 * @param {string} roastText
 * @param {'friday'|'tuesday'} [type='friday']
 * @returns {Promise<object>} Slack API response
 */
async function postRoast(channelId, roastText, type = 'friday') {
  requireApp();

  // Split the roast text into chunks of ≤2900 chars to stay within Slack's block limit
  const MAX_BLOCK_LEN = 2900;
  const chunks = [];
  let remaining = roastText;
  while (remaining.length > 0) {
    chunks.push(remaining.slice(0, MAX_BLOCK_LEN));
    remaining = remaining.slice(MAX_BLOCK_LEN);
  }

  const header = type === 'tuesday'
    ? '🚔 Office Police Midweek Check-In'
    : '🚔 Office Police Weekly Roast';

  const blocks = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: header,
        emoji: true,
      },
    },
    {
      type: 'divider',
    },
    ...chunks.map((chunk) => ({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: chunk,
      },
    })),
    {
      type: 'divider',
    },
    {
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `_Generated by Office Police • ${new Date().toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          })}_`,
        },
      ],
    },
  ];

  return _app.client.chat.postMessage({
    channel: channelId,
    text: header, // fallback for notifications
    blocks,
  });
}

export { init, postMessage, postRoast };
