/**
 * Slack Poster — Workers version. Uses fetch() directly.
 */

async function slackPost(endpoint, botToken, body) {
  const response = await fetch(`https://slack.com/api/${endpoint}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      'Authorization': `Bearer ${botToken}`,
    },
    body: JSON.stringify(body),
  });
  return response.json();
}

export async function postMessage(channelId, text, botToken) {
  return slackPost('chat.postMessage', botToken, { channel: channelId, text });
}

export async function postRoast(channelId, roastText, botToken, type = 'friday') {
  const header = type === 'tuesday'
    ? '🚔 Office Police — Midweek Check-In'
    : type === 'monthly'
    ? '🚔 Office Police — Monthly Report'
    : '🚔 Office Police — Weekly Roast';

  const MAX_BLOCK_LEN = 2900;
  const chunks = [];
  let remaining = roastText;
  while (remaining.length > 0) {
    chunks.push(remaining.slice(0, MAX_BLOCK_LEN));
    remaining = remaining.slice(MAX_BLOCK_LEN);
  }

  const blocks = [
    { type: 'header', text: { type: 'plain_text', text: header, emoji: true } },
    { type: 'divider' },
    ...chunks.map((chunk) => ({
      type: 'section',
      text: { type: 'mrkdwn', text: chunk },
    })),
    { type: 'divider' },
    {
      type: 'context',
      elements: [{
        type: 'mrkdwn',
        text: `_Generated by Office Police • ${new Date().toLocaleDateString('en-US', {
          weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
        })}_`,
      }],
    },
  ];

  return slackPost('chat.postMessage', botToken, { channel: channelId, text: header, blocks });
}

export async function getUserName(userId, botToken) {
  const data = await slackPost('users.info', botToken, { user: userId });
  if (!data.ok) return null;
  return data.user?.profile?.display_name || data.user?.profile?.real_name || data.user?.name || null;
}
